import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TweetList from '../components/TweetList'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TweetList></TweetList>
    </div>
  )
}
